<?php

return [
    'sections' => [
        'home-hero' => [
            'title' => 'Homepage hero',
            'description' => 'Bewerk de bovenste hero-sectie van de homepage.',
            'preview_url' => '/',
            'fields' => [
                ['key' => 'badge', 'label' => 'Badge', 'type' => 'text'],
                ['key' => 'title_line_1', 'label' => 'Titel regel 1', 'type' => 'text'],
                ['key' => 'title_highlight', 'label' => 'Titel accentregel', 'type' => 'text'],
                ['key' => 'description', 'label' => 'Omschrijving', 'type' => 'textarea'],
                ['key' => 'tagline', 'label' => 'Korte extra regel', 'type' => 'text'],
                ['key' => 'primary_cta_label', 'label' => 'Primaire knop tekst', 'type' => 'text'],
                ['key' => 'primary_cta_href', 'label' => 'Primaire knop link', 'type' => 'url'],
                ['key' => 'secondary_cta_label', 'label' => 'Secundaire knop tekst', 'type' => 'text'],
                ['key' => 'secondary_cta_href', 'label' => 'Secundaire knop link', 'type' => 'url'],
                [
                    'key' => 'highlights',
                    'label' => 'USP blokken',
                    'type' => 'repeater',
                    'itemLabel' => 'USP',
                    'fields' => [
                        ['key' => 'eyebrow', 'label' => 'Bovenlabel', 'type' => 'text'],
                        ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                        ['key' => 'description', 'label' => 'Omschrijving', 'type' => 'text'],
                    ],
                ],
            ],
            'defaults' => [
                'badge' => 'Alles op twee wielen, voor iedereen',
                'title_line_1' => 'Alles voor',
                'title_highlight' => 'Tweewielers',
                'description' => 'Van verkoop tot reparatie en onderhoud: wij helpen je met fietsen, e-bikes en scooters. Praktisch, eerlijk en met persoonlijke service uit Nijkerk.',
                'tagline' => 'Goed op weg begint met vertrouwen.',
                'primary_cta_label' => 'Bekijk het aanbod',
                'primary_cta_href' => '/scooters',
                'secondary_cta_label' => 'Plan onderhoud',
                'secondary_cta_href' => '/contact',
                'highlights' => [
                    ['eyebrow' => 'Verkoop', 'title' => 'Rijklaar aanbod', 'description' => 'Scooters die technisch zijn nagekeken en direct inzetbaar zijn'],
                    ['eyebrow' => 'Reparatie', 'title' => 'Snel geholpen', 'description' => 'Storingen en defecten vakkundig opgelost'],
                    ['eyebrow' => 'Onderhoud', 'title' => 'Voorkom stilstand', 'description' => 'Periodieke service voor veilige en betrouwbare kilometers'],
                ],
            ],
        ],
        'home-quality' => [
            'title' => 'Homepage kwaliteit',
            'description' => 'Bewerk de drie kwaliteitskaarten op de homepage.',
            'preview_url' => '/',
            'fields' => [
                ['key' => 'eyebrow', 'label' => 'Bovenlabel', 'type' => 'text'],
                ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                [
                    'key' => 'cards',
                    'label' => 'Kwaliteitskaarten',
                    'type' => 'repeater',
                    'itemLabel' => 'Kaart',
                    'fields' => [
                        ['key' => 'icon', 'label' => 'Icoon / afkorting', 'type' => 'text'],
                        ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                        ['key' => 'description', 'label' => 'Omschrijving', 'type' => 'textarea'],
                    ],
                ],
            ],
            'defaults' => [
                'eyebrow' => 'Onze standaard',
                'title' => 'Kwaliteit voor elk type tweewieler',
                'cards' => [
                    ['icon' => 'VK', 'title' => 'Vakkundig herstel', 'description' => 'Van remmen tot aandrijving: wij repareren met aandacht voor veiligheid en duurzaamheid.'],
                    ['icon' => 'SV', 'title' => 'Service op maat', 'description' => 'Onderhoud en advies afgestemd op jouw fiets, e-bike of scooter.'],
                    ['icon' => '€', 'title' => 'Duidelijke afspraken', 'description' => 'Heldere uitleg en transparante prijzen zonder verrassingen achteraf.'],
                ],
            ],
        ],
        'home-maintenance' => [
            'title' => 'Homepage onderhoud en reparatie',
            'description' => 'Bewerk de onderhoudssectie op de homepage. De categoriekaarten beheer je per categorie.',
            'preview_url' => '/',
            'fields' => [
                ['key' => 'eyebrow', 'label' => 'Bovenlabel', 'type' => 'text'],
                ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                ['key' => 'description', 'label' => 'Omschrijving', 'type' => 'textarea'],
            ],
            'defaults' => [
                'eyebrow' => 'Nu beschikbaar',
                'title' => 'Reparatie en onderhoud voor tweewielers',
                'description' => 'Je kunt bij ons terecht voor onderhoud en reparatie van scooters, fietsen en e-bikes. Zo blijf je veilig rijden en voorkom je onverwachte stilstand.',
            ],
        ],
        'maintenance-bike' => [
            'title' => 'Categorie: Fiets onderhoud',
            'description' => 'Bewerk onderhoudscontent voor normale fietsen.',
            'preview_url' => '/onderhoud/fiets',
            'hidden_in_site_settings' => true,
            'fields' => [
                ['key' => 'hero_image', 'label' => 'Header afbeelding', 'type' => 'image'],
                ['key' => 'eyebrow', 'label' => 'Bovenlabel', 'type' => 'text'],
                ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                ['key' => 'description', 'label' => 'Intro tekst', 'type' => 'textarea'],
                ['key' => 'card_icon', 'label' => 'Homepage kaart icoon', 'type' => 'text'],
                ['key' => 'card_title', 'label' => 'Homepage kaart titel', 'type' => 'text'],
                ['key' => 'card_description', 'label' => 'Homepage kaart beschrijving', 'type' => 'text'],
                ['key' => 'card_maintenance_href', 'label' => 'Kaart link onderhoud', 'type' => 'url'],
                ['key' => 'card_sales_href', 'label' => 'Kaart link verkoop', 'type' => 'url'],
                ['key' => 'small_badge', 'label' => 'Kleine beurt badge', 'type' => 'text'],
                ['key' => 'small_title', 'label' => 'Kleine beurt titel', 'type' => 'text'],
                ['key' => 'small_description', 'label' => 'Kleine beurt omschrijving', 'type' => 'textarea'],
                ['key' => 'small_items', 'label' => 'Kleine beurt werkzaamheden', 'type' => 'textarea'],
                ['key' => 'small_price_label', 'label' => 'Kleine beurt prijslabel', 'type' => 'text'],
                ['key' => 'small_price', 'label' => 'Kleine beurt prijs', 'type' => 'text'],
                ['key' => 'large_badge', 'label' => 'Grote beurt badge', 'type' => 'text'],
                ['key' => 'large_title', 'label' => 'Grote beurt titel', 'type' => 'text'],
                ['key' => 'large_description', 'label' => 'Grote beurt omschrijving', 'type' => 'textarea'],
                ['key' => 'large_items', 'label' => 'Grote beurt werkzaamheden', 'type' => 'textarea'],
                ['key' => 'large_price_label', 'label' => 'Grote beurt prijslabel', 'type' => 'text'],
                ['key' => 'large_price', 'label' => 'Grote beurt prijs', 'type' => 'text'],
            ],
            'defaults' => [
                'hero_image' => '',
                'eyebrow' => 'Onderhoud Fiets',
                'title' => 'Fiets onderhoud en service',
                'description' => 'Voor stadsfietsen en hybride fietsen voeren wij onderhoud uit op remmen, aandrijving, lagers en veiligheid.',
                'card_icon' => '🚴',
                'card_title' => 'Fiets onderhoud',
                'card_description' => 'Voor dagelijkse fietsen met focus op veiligheid en comfort.',
                'card_maintenance_href' => '/onderhoud/fiets',
                'card_sales_href' => '/verkoop/fiets',
                'small_badge' => 'Kleine beurt',
                'small_title' => 'Basis onderhoud Fiets',
                'small_description' => 'Reguliere controle en afstelling voor dagelijks gebruik.',
                'small_items' => '<ul><li>Bandenspanning en profielcontrole</li><li>Remblokken en remkabels controleren</li><li>Ketting reinigen en smeren</li><li>Versnellingen afstellen</li><li>Verlichting en reflectie controleren</li></ul>',
                'small_price_label' => 'Prijs',
                'small_price' => 'Vanaf EUR 45',
                'large_badge' => 'Grote beurt',
                'large_title' => 'Complete Fiets service',
                'large_description' => 'Uitgebreide onderhoudsbeurt voor maximale betrouwbaarheid.',
                'large_items' => '<ul><li>Alles uit de kleine beurt</li><li>Wielen richten en controleren op spaakspanning</li><li>Trapas en balhoofd controleren op slijtage</li><li>Diepte-reiniging aandrijflijn</li><li>Proefrit en eindinspectie</li></ul>',
                'large_price_label' => 'Prijs',
                'large_price' => 'Vanaf EUR 89',
            ],
        ],
        'maintenance-ebike' => [
            'title' => 'Categorie: E-bike onderhoud',
            'description' => 'Bewerk de E-bike onderhoudspagina.',
            'preview_url' => '/onderhoud/e-bike',
            'hidden_in_site_settings' => true,
            'fields' => [
                ['key' => 'hero_image', 'label' => 'Header afbeelding', 'type' => 'image'],
                ['key' => 'eyebrow', 'label' => 'Bovenlabel', 'type' => 'text'],
                ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                ['key' => 'description', 'label' => 'Intro tekst', 'type' => 'textarea'],
                ['key' => 'card_icon', 'label' => 'Homepage kaart icoon', 'type' => 'text'],
                ['key' => 'card_title', 'label' => 'Homepage kaart titel', 'type' => 'text'],
                ['key' => 'card_description', 'label' => 'Homepage kaart beschrijving', 'type' => 'text'],
                ['key' => 'card_maintenance_href', 'label' => 'Kaart link onderhoud', 'type' => 'url'],
                ['key' => 'card_sales_href', 'label' => 'Kaart link verkoop', 'type' => 'url'],
                ['key' => 'small_badge', 'label' => 'Kleine beurt badge', 'type' => 'text'],
                ['key' => 'small_title', 'label' => 'Kleine beurt titel', 'type' => 'text'],
                ['key' => 'small_description', 'label' => 'Kleine beurt omschrijving', 'type' => 'textarea'],
                ['key' => 'small_items', 'label' => 'Kleine beurt werkzaamheden', 'type' => 'textarea'],
                ['key' => 'small_price_label', 'label' => 'Kleine beurt prijslabel', 'type' => 'text'],
                ['key' => 'small_price', 'label' => 'Kleine beurt prijs', 'type' => 'text'],
                ['key' => 'large_badge', 'label' => 'Grote beurt badge', 'type' => 'text'],
                ['key' => 'large_title', 'label' => 'Grote beurt titel', 'type' => 'text'],
                ['key' => 'large_description', 'label' => 'Grote beurt omschrijving', 'type' => 'textarea'],
                ['key' => 'large_items', 'label' => 'Grote beurt werkzaamheden', 'type' => 'textarea'],
                ['key' => 'large_price_label', 'label' => 'Grote beurt prijslabel', 'type' => 'text'],
                ['key' => 'large_price', 'label' => 'Grote beurt prijs', 'type' => 'text'],
            ],
            'defaults' => [
                'hero_image' => '',
                'eyebrow' => 'Onderhoud E-bike',
                'title' => 'E-bike onderhoud en service',
                'description' => 'Voor e-bikes voeren wij onderhoud uit met aandacht voor veiligheid, software, elektronica en soepel rijgedrag.',
                'card_icon' => '⚡',
                'card_title' => 'E-bike onderhoud',
                'card_description' => 'Voor betrouwbare ondersteuning, remkracht en actieradius.',
                'card_maintenance_href' => '/onderhoud/e-bike',
                'card_sales_href' => '/verkoop/e-bike',
                'small_badge' => 'Kleine beurt',
                'small_title' => 'Basis onderhoud E-bike',
                'small_description' => 'Reguliere controle en afstelling voor dagelijks veilig gebruik.',
                'small_items' => '<ul><li>Remmen en schijfslijtage controleren</li><li>Bandenspanning en profiel checken</li><li>Ketting/reinigen/smeren en versnellingen afstellen</li><li>Accu- en laadcontacten controleren</li><li>Verlichting en display-functies testen</li></ul>',
                'small_price_label' => 'Prijs',
                'small_price' => 'Vanaf EUR 59',
                'large_badge' => 'Grote beurt',
                'large_title' => 'Complete E-bike service',
                'large_description' => 'Uitgebreide onderhoudsbeurt inclusief aandrijving en elektrische checks.',
                'large_items' => '<ul><li>Alles uit de kleine beurt</li><li>Aandrijflijn diepte-reiniging en afstelling</li><li>Motorondersteuning en sensoren controleren</li><li>Software/firmware update waar mogelijk</li><li>Wielspanning en lagers nalopen</li></ul>',
                'large_price_label' => 'Prijs',
                'large_price' => 'Vanaf EUR 109',
            ],
        ],
        'maintenance-fatbike' => [
            'title' => 'Categorie: Fatbike onderhoud',
            'description' => 'Bewerk de Fatbike onderhoudspagina.',
            'preview_url' => '/onderhoud/fatbike',
            'hidden_in_site_settings' => true,
            'fields' => [
                ['key' => 'hero_image', 'label' => 'Header afbeelding', 'type' => 'image'],
                ['key' => 'eyebrow', 'label' => 'Bovenlabel', 'type' => 'text'],
                ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                ['key' => 'description', 'label' => 'Intro tekst', 'type' => 'textarea'],
                ['key' => 'card_icon', 'label' => 'Homepage kaart icoon', 'type' => 'text'],
                ['key' => 'card_title', 'label' => 'Homepage kaart titel', 'type' => 'text'],
                ['key' => 'card_description', 'label' => 'Homepage kaart beschrijving', 'type' => 'text'],
                ['key' => 'card_maintenance_href', 'label' => 'Kaart link onderhoud', 'type' => 'url'],
                ['key' => 'card_sales_href', 'label' => 'Kaart link verkoop', 'type' => 'url'],
                ['key' => 'small_badge', 'label' => 'Kleine beurt badge', 'type' => 'text'],
                ['key' => 'small_title', 'label' => 'Kleine beurt titel', 'type' => 'text'],
                ['key' => 'small_description', 'label' => 'Kleine beurt omschrijving', 'type' => 'textarea'],
                ['key' => 'small_items', 'label' => 'Kleine beurt werkzaamheden', 'type' => 'textarea'],
                ['key' => 'small_price_label', 'label' => 'Kleine beurt prijslabel', 'type' => 'text'],
                ['key' => 'small_price', 'label' => 'Kleine beurt prijs', 'type' => 'text'],
                ['key' => 'large_badge', 'label' => 'Grote beurt badge', 'type' => 'text'],
                ['key' => 'large_title', 'label' => 'Grote beurt titel', 'type' => 'text'],
                ['key' => 'large_description', 'label' => 'Grote beurt omschrijving', 'type' => 'textarea'],
                ['key' => 'large_items', 'label' => 'Grote beurt werkzaamheden', 'type' => 'textarea'],
                ['key' => 'large_price_label', 'label' => 'Grote beurt prijslabel', 'type' => 'text'],
                ['key' => 'large_price', 'label' => 'Grote beurt prijs', 'type' => 'text'],
            ],
            'defaults' => [
                'hero_image' => '',
                'eyebrow' => 'Onderhoud Fatbike',
                'title' => 'Fatbike onderhoud en service',
                'description' => 'Fatbikes vragen extra aandacht voor banden, remmen en framebelasting. Wij zorgen dat jouw fatbike veilig en strak blijft rijden.',
                'card_icon' => '🚲',
                'card_title' => 'Fatbike onderhoud',
                'card_description' => 'Extra aandacht voor remmen, banden en elektrische componenten.',
                'card_maintenance_href' => '/onderhoud/fatbike',
                'card_sales_href' => '/verkoop/fatbike',
                'small_badge' => 'Kleine beurt',
                'small_title' => 'Basis onderhoud Fatbike',
                'small_description' => 'Controle en afstelling voor dagelijks gebruik.',
                'small_items' => '<ul><li>Bandenspanning en profielcontrole</li><li>Remmen controleren en afstellen</li><li>Ketting en tandwielen reinigen/smeren</li><li>Bouten en framecontrole op speling</li><li>Verlichting en elektrische functies testen</li></ul>',
                'small_price_label' => 'Prijs',
                'small_price' => 'Vanaf EUR 55',
                'large_badge' => 'Grote beurt',
                'large_title' => 'Complete Fatbike service',
                'large_description' => 'Uitgebreide servicebeurt voor intensief gebruik.',
                'large_items' => '<ul><li>Alles uit de kleine beurt</li><li>Remblokken/slijtagecontrole en waar nodig vervanging</li><li>Wielspanning en uitlijning controleren</li><li>Balhoofd en trapas op slijtage nalopen</li><li>Volledige eindcontrole en proefrit</li></ul>',
                'large_price_label' => 'Prijs',
                'large_price' => 'Vanaf EUR 99',
            ],
        ],
        'maintenance-scooter' => [
            'title' => 'Categorie: Scooter onderhoud',
            'description' => 'Bewerk de Scooter onderhoudspagina.',
            'preview_url' => '/onderhoud/scooter',
            'hidden_in_site_settings' => true,
            'fields' => [
                ['key' => 'hero_image', 'label' => 'Header afbeelding', 'type' => 'image'],
                ['key' => 'eyebrow', 'label' => 'Bovenlabel', 'type' => 'text'],
                ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                ['key' => 'description', 'label' => 'Intro tekst', 'type' => 'textarea'],
                ['key' => 'card_icon', 'label' => 'Homepage kaart icoon', 'type' => 'text'],
                ['key' => 'card_title', 'label' => 'Homepage kaart titel', 'type' => 'text'],
                ['key' => 'card_description', 'label' => 'Homepage kaart beschrijving', 'type' => 'text'],
                ['key' => 'card_maintenance_href', 'label' => 'Kaart link onderhoud', 'type' => 'url'],
                ['key' => 'card_sales_href', 'label' => 'Kaart link verkoop', 'type' => 'url'],
                ['key' => 'small_badge', 'label' => 'Kleine beurt badge', 'type' => 'text'],
                ['key' => 'small_title', 'label' => 'Kleine beurt titel', 'type' => 'text'],
                ['key' => 'small_description', 'label' => 'Kleine beurt omschrijving', 'type' => 'textarea'],
                ['key' => 'small_items', 'label' => 'Kleine beurt werkzaamheden', 'type' => 'textarea'],
                ['key' => 'small_price_label', 'label' => 'Kleine beurt prijslabel', 'type' => 'text'],
                ['key' => 'small_price', 'label' => 'Kleine beurt prijs', 'type' => 'text'],
                ['key' => 'large_badge', 'label' => 'Grote beurt badge', 'type' => 'text'],
                ['key' => 'large_title', 'label' => 'Grote beurt titel', 'type' => 'text'],
                ['key' => 'large_description', 'label' => 'Grote beurt omschrijving', 'type' => 'textarea'],
                ['key' => 'large_items', 'label' => 'Grote beurt werkzaamheden', 'type' => 'textarea'],
                ['key' => 'large_price_label', 'label' => 'Grote beurt prijslabel', 'type' => 'text'],
                ['key' => 'large_price', 'label' => 'Grote beurt prijs', 'type' => 'text'],
            ],
            'defaults' => [
                'hero_image' => '',
                'eyebrow' => 'Onderhoud Scooter',
                'title' => 'Scooter onderhoud en service',
                'description' => 'Van dagelijkse stadsritten tot langere afstanden: met tijdig onderhoud blijft je scooter veilig en betrouwbaar.',
                'card_icon' => '🛵',
                'card_title' => 'Scooter onderhoud',
                'card_description' => 'Van kleine beurt tot complete service voor veilig rijplezier.',
                'card_maintenance_href' => '/onderhoud/scooter',
                'card_sales_href' => '/verkoop/scooter',
                'small_badge' => 'Kleine beurt',
                'small_title' => 'Basis onderhoud Scooter',
                'small_description' => 'Periodiek onderhoud voor soepel en veilig rijden.',
                'small_items' => '<ul><li>Motorolie verversen</li><li>Bougie controleren/vervangen</li><li>Bandenspanning en profiel controleren</li><li>Remmen controleren en afstellen</li><li>Accu en verlichting testen</li></ul>',
                'small_price_label' => 'Prijs',
                'small_price' => 'Vanaf EUR 79',
                'large_badge' => 'Grote beurt',
                'large_title' => 'Complete Scooter service',
                'large_description' => 'Uitgebreide onderhoudsbeurt inclusief aandrijving en eindcontrole.',
                'large_items' => '<ul><li>Alles uit de kleine beurt</li><li>Variateur en V-snaar controleren</li><li>Kleppen stellen (indien van toepassing)</li><li>Remsysteem grondig nalopen</li><li>Proefrit en volledige eindinspectie</li></ul>',
                'large_price_label' => 'Prijs',
                'large_price' => 'Vanaf EUR 159',
            ],
        ],
        'sales-bike' => [
            'title' => 'Categorie: Fiets verkoop',
            'description' => 'Bewerk de verkooppagina van normale fietsen.',
            'preview_url' => '/verkoop/fiets',
            'hidden_in_site_settings' => true,
            'fields' => [
                ['key' => 'hero_image', 'label' => 'Header afbeelding', 'type' => 'image'],
                ['key' => 'eyebrow', 'label' => 'Bovenlabel', 'type' => 'text'],
                ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                ['key' => 'description', 'label' => 'Subtitel', 'type' => 'textarea'],
                ['key' => 'intro_title', 'label' => 'Intro titel', 'type' => 'text'],
                ['key' => 'intro_text', 'label' => 'Intro tekst', 'type' => 'textarea'],
                ['key' => 'usp_items', 'label' => 'USP lijst', 'type' => 'textarea'],
                ['key' => 'primary_cta_label', 'label' => 'Primaire knop tekst', 'type' => 'text'],
                ['key' => 'primary_cta_href', 'label' => 'Primaire knop link', 'type' => 'url'],
                ['key' => 'secondary_cta_label', 'label' => 'Secundaire knop tekst', 'type' => 'text'],
                ['key' => 'secondary_cta_href', 'label' => 'Secundaire knop link', 'type' => 'url'],
            ],
            'defaults' => [
                'hero_image' => '',
                'eyebrow' => 'Verkoop Fiets',
                'title' => 'Fietsen te koop',
                'description' => 'Betrouwbare fietsen voor dagelijks gebruik, woon-werk en vrije tijd.',
                'intro_title' => 'Wat je van ons mag verwachten',
                'intro_text' => 'Elke fiets wordt nagelopen en rijklaar geleverd. Zo ga je zorgeloos de weg op.',
                'usp_items' => '<ul><li>Rijklaar afgeleverd</li><li>Technisch gecontroleerd</li><li>Heldere prijsafspraken</li></ul>',
                'primary_cta_label' => 'Neem contact op',
                'primary_cta_href' => '/contact',
                'secondary_cta_label' => 'Plan onderhoud',
                'secondary_cta_href' => '/onderhoud/fiets',
            ],
        ],
        'sales-ebike' => [
            'title' => 'Categorie: E-bike verkoop',
            'description' => 'Bewerk de verkooppagina van E-bikes.',
            'preview_url' => '/verkoop/e-bike',
            'hidden_in_site_settings' => true,
            'fields' => [
                ['key' => 'hero_image', 'label' => 'Header afbeelding', 'type' => 'image'],
                ['key' => 'eyebrow', 'label' => 'Bovenlabel', 'type' => 'text'],
                ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                ['key' => 'description', 'label' => 'Subtitel', 'type' => 'textarea'],
                ['key' => 'intro_title', 'label' => 'Intro titel', 'type' => 'text'],
                ['key' => 'intro_text', 'label' => 'Intro tekst', 'type' => 'textarea'],
                ['key' => 'usp_items', 'label' => 'USP lijst', 'type' => 'textarea'],
                ['key' => 'primary_cta_label', 'label' => 'Primaire knop tekst', 'type' => 'text'],
                ['key' => 'primary_cta_href', 'label' => 'Primaire knop link', 'type' => 'url'],
                ['key' => 'secondary_cta_label', 'label' => 'Secundaire knop tekst', 'type' => 'text'],
                ['key' => 'secondary_cta_href', 'label' => 'Secundaire knop link', 'type' => 'url'],
            ],
            'defaults' => [
                'hero_image' => '',
                'eyebrow' => 'Verkoop E-bike',
                'title' => 'E-bikes te koop',
                'description' => 'Comfortabele en krachtige e-bikes, klaar voor dagelijks gebruik.',
                'intro_title' => 'Zekerheid bij aankoop',
                'intro_text' => 'We helpen je met de juiste framemaat, accukeuze en service na aankoop.',
                'usp_items' => '<ul><li>Accu en elektronica nagekeken</li><li>Rijklaar afgeleverd</li><li>Advies op maat</li></ul>',
                'primary_cta_label' => 'Neem contact op',
                'primary_cta_href' => '/contact',
                'secondary_cta_label' => 'Plan onderhoud',
                'secondary_cta_href' => '/onderhoud/e-bike',
            ],
        ],
        'sales-fatbike' => [
            'title' => 'Categorie: Fatbike verkoop',
            'description' => 'Bewerk de verkooppagina van Fatbikes.',
            'preview_url' => '/verkoop/fatbike',
            'hidden_in_site_settings' => true,
            'fields' => [
                ['key' => 'hero_image', 'label' => 'Header afbeelding', 'type' => 'image'],
                ['key' => 'eyebrow', 'label' => 'Bovenlabel', 'type' => 'text'],
                ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                ['key' => 'description', 'label' => 'Subtitel', 'type' => 'textarea'],
                ['key' => 'intro_title', 'label' => 'Intro titel', 'type' => 'text'],
                ['key' => 'intro_text', 'label' => 'Intro tekst', 'type' => 'textarea'],
                ['key' => 'usp_items', 'label' => 'USP lijst', 'type' => 'textarea'],
                ['key' => 'primary_cta_label', 'label' => 'Primaire knop tekst', 'type' => 'text'],
                ['key' => 'primary_cta_href', 'label' => 'Primaire knop link', 'type' => 'url'],
                ['key' => 'secondary_cta_label', 'label' => 'Secundaire knop tekst', 'type' => 'text'],
                ['key' => 'secondary_cta_href', 'label' => 'Secundaire knop link', 'type' => 'url'],
            ],
            'defaults' => [
                'hero_image' => '',
                'eyebrow' => 'Verkoop Fatbike',
                'title' => 'Fatbikes te koop',
                'description' => 'Stoere fatbikes met grip, comfort en een opvallende uitstraling.',
                'intro_title' => 'Klaar voor stad en avontuur',
                'intro_text' => 'Wij leveren fatbikes rijklaar met aandacht voor veiligheid en duurzaamheid.',
                'usp_items' => '<ul><li>Remmen en banden gecontroleerd</li><li>Elektrische onderdelen nagekeken</li><li>Heldere uitleg bij aflevering</li></ul>',
                'primary_cta_label' => 'Neem contact op',
                'primary_cta_href' => '/contact',
                'secondary_cta_label' => 'Plan onderhoud',
                'secondary_cta_href' => '/onderhoud/fatbike',
            ],
        ],
        'sales-scooter' => [
            'title' => 'Categorie: Scooter verkoop',
            'description' => 'Bewerk de verkooppagina van Scooters.',
            'preview_url' => '/verkoop/scooter',
            'hidden_in_site_settings' => true,
            'fields' => [
                ['key' => 'hero_image', 'label' => 'Header afbeelding', 'type' => 'image'],
                ['key' => 'eyebrow', 'label' => 'Bovenlabel', 'type' => 'text'],
                ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                ['key' => 'description', 'label' => 'Subtitel', 'type' => 'textarea'],
                ['key' => 'intro_title', 'label' => 'Intro titel', 'type' => 'text'],
                ['key' => 'intro_text', 'label' => 'Intro tekst', 'type' => 'textarea'],
                ['key' => 'usp_items', 'label' => 'USP lijst', 'type' => 'textarea'],
                ['key' => 'primary_cta_label', 'label' => 'Primaire knop tekst', 'type' => 'text'],
                ['key' => 'primary_cta_href', 'label' => 'Primaire knop link', 'type' => 'url'],
                ['key' => 'secondary_cta_label', 'label' => 'Secundaire knop tekst', 'type' => 'text'],
                ['key' => 'secondary_cta_href', 'label' => 'Secundaire knop link', 'type' => 'url'],
            ],
            'defaults' => [
                'hero_image' => '',
                'eyebrow' => 'Verkoop Scooter',
                'title' => 'Scooters te koop',
                'description' => 'Direct beschikbare scooters met service, onderhoudshistorie en duidelijke afspraken.',
                'intro_title' => 'Rijklaar en gecontroleerd',
                'intro_text' => 'Onze scooters zijn technisch nagekeken zodat je met vertrouwen kunt rijden.',
                'usp_items' => '<ul><li>Rijklaar afleveren</li><li>Transparante prijs</li><li>Onderhoud en nazorg mogelijk</li></ul>',
                'primary_cta_label' => 'Bekijk aanbod',
                'primary_cta_href' => '/scooters',
                'secondary_cta_label' => 'Neem contact op',
                'secondary_cta_href' => '/contact',
            ],
        ],
        'home-featured' => [
            'title' => 'Homepage nieuwste aanbod',
            'description' => 'Bewerk kopteksten en link van het nieuwste aanbod op de homepage.',
            'preview_url' => '/',
            'fields' => [
                ['key' => 'eyebrow', 'label' => 'Bovenlabel', 'type' => 'text'],
                ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                ['key' => 'description', 'label' => 'Omschrijving', 'type' => 'text'],
                ['key' => 'link_label', 'label' => 'Link tekst', 'type' => 'text'],
                ['key' => 'link_href', 'label' => 'Link URL', 'type' => 'url'],
            ],
            'defaults' => [
                'eyebrow' => 'Actueel',
                'title' => 'Ons aanbod',
                'description' => 'Rijklaar geselecteerd en direct beschikbaar',
                'link_label' => 'Bekijk aanbod →',
                'link_href' => '/scooters',
            ],
        ],
        'home-cta' => [
            'title' => 'Homepage CTA',
            'description' => 'Bewerk de oranje call-to-action op de homepage.',
            'preview_url' => '/',
            'fields' => [
                ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                ['key' => 'description', 'label' => 'Omschrijving', 'type' => 'textarea'],
                ['key' => 'button_label', 'label' => 'Knop tekst', 'type' => 'text'],
                ['key' => 'button_href', 'label' => 'Knop URL', 'type' => 'url'],
            ],
            'defaults' => [
                'title' => 'Hulp nodig met jouw tweewieler?',
                'description' => 'Of je nu wilt kopen, repareren of onderhouden: wij denken met je mee en helpen je snel weer op weg.',
                'button_label' => 'Neem contact op',
                'button_href' => '/contact',
            ],
        ],
        'home-info' => [
            'title' => 'Homepage onderblok',
            'description' => 'Bewerk het tekstblok onderaan de homepage.',
            'preview_url' => '/',
            'fields' => [
                ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                ['key' => 'description', 'label' => 'Omschrijving', 'type' => 'textarea'],
                [
                    'key' => 'links',
                    'label' => 'Snelkoppelingen',
                    'type' => 'repeater',
                    'itemLabel' => 'Link',
                    'fields' => [
                        ['key' => 'label', 'label' => 'Tekst', 'type' => 'text'],
                        ['key' => 'href', 'label' => 'URL', 'type' => 'url'],
                    ],
                ],
            ],
            'defaults' => [
                'title' => 'Alles voor tweewielers in Nijkerk',
                'description' => 'Goed Op Weg Nijkerk helpt je met verkoop, reparatie en onderhoud van tweewielers. Van scooter tot e-bike: je krijgt heldere uitleg, eerlijke service en een aanpak waar je op kunt vertrouwen.',
                'links' => [
                    ['label' => 'Bekijk scooters te koop', 'href' => '/scooters'],
                    ['label' => 'Plan reparatie of onderhoud', 'href' => '/contact'],
                    ['label' => 'Lees veelgestelde vragen', 'href' => '/faq'],
                ],
            ],
        ],
        'shop-hero' => [
            'title' => 'Scooters pagina hero',
            'description' => 'Bewerk de kop van de scooters-pagina.',
            'preview_url' => '/scooters',
            'fields' => [
                ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                ['key' => 'count_label_singular', 'label' => 'Tekst bij 1 scooter', 'type' => 'text'],
                ['key' => 'count_label_plural', 'label' => 'Tekst bij meerdere scooters', 'type' => 'text'],
            ],
            'defaults' => [
                'title' => 'Scooter aanbod binnen onze tweewieler service',
                'count_label_singular' => 'scooter direct beschikbaar',
                'count_label_plural' => 'scooters direct beschikbaar',
            ],
        ],
        'shop-info' => [
            'title' => 'Scooters pagina onderblok',
            'description' => 'Bewerk het informatieve blok onder de scooterlijst.',
            'preview_url' => '/scooters',
            'fields' => [
                ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                ['key' => 'description', 'label' => 'Omschrijving', 'type' => 'textarea'],
                [
                    'key' => 'links',
                    'label' => 'Actielinks',
                    'type' => 'repeater',
                    'itemLabel' => 'Link',
                    'fields' => [
                        ['key' => 'label', 'label' => 'Tekst', 'type' => 'text'],
                        ['key' => 'href', 'label' => 'URL', 'type' => 'url'],
                    ],
                ],
            ],
            'defaults' => [
                'title' => 'Aanbod met service, onderhoud en duidelijke historie',
                'description' => 'Ons scooteraanbod is onderdeel van een bredere tweewieler-aanpak. Je ziet per model wat er gedaan is, wat de technische staat is en hoe je eenvoudig onderhoud, reparatie of een proefrit kunt plannen.',
                'links' => [
                    ['label' => 'Garantie en veelgestelde vragen', 'href' => '/faq'],
                    ['label' => 'Plan reparatie of onderhoud', 'href' => '/contact'],
                    ['label' => 'Onderhoudstips en updates', 'href' => '/blog'],
                    ['label' => 'Terug naar homepage', 'href' => '/'],
                ],
            ],
        ],
        'faq-hero' => [
            'title' => 'FAQ hero',
            'description' => 'Bewerk de kop van de FAQ pagina.',
            'preview_url' => '/faq',
            'fields' => [
                ['key' => 'icon', 'label' => 'Icoon', 'type' => 'text'],
                ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                ['key' => 'description', 'label' => 'Omschrijving', 'type' => 'textarea'],
            ],
            'defaults' => [
                'icon' => '❓',
                'title' => 'Veelgestelde vragen',
                'description' => 'Alles wat je moet weten over onze garantie, onderhoud en service.',
            ],
        ],
        'faq-questions' => [
            'title' => 'FAQ vragen',
            'description' => 'Beheer de vragen en antwoorden op de FAQ pagina.',
            'preview_url' => '/faq',
            'fields' => [
                [
                    'key' => 'items',
                    'label' => 'Vragen',
                    'type' => 'repeater',
                    'itemLabel' => 'Vraag',
                    'fields' => [
                        ['key' => 'question', 'label' => 'Vraag', 'type' => 'text'],
                        ['key' => 'answer', 'label' => 'Antwoord', 'type' => 'textarea'],
                    ],
                ],
            ],
            'defaults' => [
                'items' => [
                    ['question' => 'Zit er garantie op de scooters van Goed op Weg Nijkerk?', 'answer' => "Ja, absoluut. Wij staan achter de kwaliteit van de scooters die wij opknappen. Daarom leveren wij al onze scooters standaard met een vaste garantieregeling op het motorblok en de accu.\n\nVraag bij de aankoop naar de exacte garantietermijn van jouw scooter."],
                    ['question' => 'Wat houdt de gratis eerste onderhoudsbeurt in?', 'answer' => "Bij de all-in prijs van je scooter zit een gratis controle- en onderhoudsbeurt inbegrepen. We adviseren om hiervoor een afspraak te maken zodra je 1.500 kilometer hebt gereden of na 6 maanden.\n\nTijdens deze beurt lopen we de scooter volledig na: we verversen de motorolie, controleren de bougie en filters en stellen de remmen en bandenspanning af."],
                    ['question' => 'Wat valt er buiten de garantie?', 'answer' => "De garantie dekt vitale onderdelen zoals het motorblok en de elektronica. Slijtageonderdelen die door gebruik minder worden of kapot kunnen gaan, vallen hierbuiten.\n\nDenk hierbij aan banden, remblokken, lampjes en schade die is ontstaan door vallen of een ongeluk."],
                    ['question' => 'Kan ik ook mijn oude scooter aan jullie verkopen?', 'answer' => "Zeker. Heb je nog een scooter in de schuur staan die niet meer start, schade heeft of waar je simpelweg vanaf wilt? Wij kopen ook opknappers in.\n\nNeem contact met ons op, stuur een paar foto's en de details door, en we kijken of we een mooie deal kunnen maken."],
                    ['question' => 'Kan ik langskomen voor een proefrit?', 'answer' => "Natuurlijk. Als je een mooie scooter op onze website hebt gezien, ben je van harte welkom om hem in het echt te komen bekijken en een proefrit te maken.\n\nNeem vooraf even contact met ons op om een moment af te spreken."],
                ],
            ],
        ],
        'faq-cta' => [
            'title' => 'FAQ CTA',
            'description' => 'Bewerk de call-to-action onderaan de FAQ pagina.',
            'preview_url' => '/faq',
            'fields' => [
                ['key' => 'title', 'label' => 'Titel', 'type' => 'text'],
                ['key' => 'description', 'label' => 'Omschrijving', 'type' => 'textarea'],
                ['key' => 'button_label', 'label' => 'Knop tekst', 'type' => 'text'],
                ['key' => 'button_href', 'label' => 'Knop URL', 'type' => 'url'],
            ],
            'defaults' => [
                'title' => 'Nog vragen?',
                'description' => 'Neem gerust contact met ons op. We helpen je graag verder met alles wat je wilt weten.',
                'button_label' => '💬 Neem contact op',
                'button_href' => '/chat',
            ],
        ],
        'admin-whatsapp' => [
            'title' => 'WhatsApp contactnummer',
            'description' => 'Stel het WhatsApp nummer in dat wordt weergegeven in de WhatsApp knop.',
            'fields' => [
                ['key' => 'whatsapp_number', 'label' => 'WhatsApp nummer', 'type' => 'text', 'help' => 'Gebruik international format (bijv. 31683575477)'],
            ],
            'defaults' => [
                'whatsapp_number' => '31683575477',
            ],
        ],
    ],
];
